Abkhazia = 
{
	["id"] = 18,
	["objects"] = 
	{
		["Cargos"] = 
		{
			[1] = "uh1h_cargo",
			[2] = "ammo_cargo",
			[3] = "barrels_cargo",
			[4] = "m117_cargo",
			[5] = "iso_container",
			[6] = "iso_container_small",
			[7] = "f_bar_cargo",
			[8] = "container_cargo",
			[9] = "tetrapod_cargo",
			[10] = "fueltank_cargo",
			[11] = "oiltank_cargo",
			[12] = "pipes_small_cargo",
			[13] = "pipes_big_cargo",
			[14] = "trunks_small_cargo",
			[15] = "trunks_long_cargo",
		}, -- end of ["Cargos"]
		["Heliports"] = 
		{
			[1] = "FARP",
			[2] = "SINGLE_HELIPAD",
		}, -- end of ["Heliports"]
		["Ships"] = 
		{
			[1] = "speedboat",
			[2] = "ELNYA",
			[3] = "MOLNIYA",
			[4] = "ZWEZDNY",
			[5] = "Dry-cargo ship-1",
			[6] = "Dry-cargo ship-2",
		}, -- end of ["Ships"]
		["Helicopters"] = 
		{
			[1] = "Mi-24V",
			[2] = "Mi-8MT",
			[3] = "Ka-50",
			[4] = "UH-1H",
			[5] = "Mi-24P",
		}, -- end of ["Helicopters"]
		["GrassAirfields"] = 
		{
			[1] = "GrassAirfield",
		}, -- end of ["GrassAirfields"]
		["Fortifications"] = 
		{
			[1] = "Locomotive",
			[2] = "Electric locomotive",
			[3] = "Coach a tank yellow",
			[4] = "Coach a tank blue",
			[5] = "Coach cargo",
			[6] = "Coach cargo open",
			[7] = "Coach a platform",
			[8] = "Coach a passenger",
			[9] = ".Command Center",
			[10] = "Hangar A",
			[11] = "Tech hangar A",
			[12] = "Farm A",
			[13] = "Farm B",
			[14] = "Garage A",
			[15] = "Boiler-house A",
			[16] = "Restaurant 1",
			[17] = "Comms tower M",
			[18] = "Cafe",
			[19] = "Workshop A",
			[20] = "Electric power box",
			[21] = "Supermarket A",
			[22] = "Water tower A",
			[23] = "TV tower",
			[24] = "Shelter",
			[25] = "Repair workshop",
			[26] = "Railway station",
			[27] = "Railway crossing A",
			[28] = "Railway crossing B",
			[29] = "WC",
			[30] = "Small house 1A area",
			[31] = "Small house 1A",
			[32] = "Small house 1B area",
			[33] = "Small house 1B",
			[34] = "Small house 1C area",
			[35] = "Small house 2C",
			[36] = "Shop",
			[37] = "Tech combine",
			[38] = "Chemical tank A",
			[39] = "Small werehouse 1",
			[40] = "Small werehouse 2",
			[41] = "Small werehouse 3",
			[42] = "Small werehouse 4",
			[43] = "Garage B",
			[44] = "Garage small A",
			[45] = "Garage small B",
			[46] = "Pump station",
			[47] = "Oil derrick",
			[48] = "Container red 1",
			[49] = "Container red 2",
			[50] = "Container red 3",
			[51] = "Container white",
			[52] = "Container brown",
			[53] = "Barracks 2",
			[54] = "Military staff",
			[55] = "Hangar B",
			[56] = "Fuel tank",
			[57] = "Shelter B",
			[58] = "Oil platform",
			[59] = "Subsidiary structure 1",
			[60] = "Subsidiary structure 2",
			[61] = "Subsidiary structure 3",
			[62] = "Subsidiary structure A",
			[63] = "Subsidiary structure B",
			[64] = "Subsidiary structure C",
			[65] = "Subsidiary structure D",
			[66] = "Subsidiary structure E",
			[67] = "Subsidiary structure F",
			[68] = "Subsidiary structure G",
			[69] = "Landmine",
			[70] = "FARP Ammo Dump Coating",
			[71] = "FARP Tent",
			[72] = "FARP CP Blindage",
			[73] = "FARP Fuel Depot",
			[74] = "GeneratorF",
			[75] = "Airshow_Cone",
			[76] = "Airshow_Crowd",
			[77] = "Red_Flag",
			[78] = "White_Flag",
			[79] = "Black_Tyre",
			[80] = "White_Tyre",
			[81] = "Black_Tyre_RF",
			[82] = "Black_Tyre_WF",
			[83] = "Windsock",
		}, -- end of ["Fortifications"]
		["Effects"] = 
		{
			[1] = "big_smoke",
			[2] = "smoky_marker",
			[3] = "smoking_line",
			[4] = "dust_smoke",
		}, -- end of ["Effects"]
		["Cars"] = 
		{
			[1] = "Bunker",
			[2] = "Sandbox",
			[3] = "house1arm",
			[4] = "house2arm",
			[5] = "outpost_road",
			[6] = "outpost",
			[7] = "houseA_arm",
			[8] = "TACAN_beacon",
			[9] = "2B11 mortar",
			[10] = "2S6 Tunguska",
			[11] = "ATMZ-5",
			[12] = "ATZ-10",
			[13] = "BMD-1",
			[14] = "BMP-1",
			[15] = "BMP-2",
			[16] = "BRDM-2",
			[17] = "BTR_D",
			[18] = "BTR-80",
			[19] = "Dog Ear radar",
			[20] = "GAZ-3307",
			[21] = "GAZ-3308",
			[22] = "GAZ-66",
			[23] = "Grad-URAL",
			[24] = "IKARUS Bus",
			[25] = "Infantry AK Ins",
			[26] = "KAMAZ Truck",
			[27] = "Kub 1S91 str",
			[28] = "Kub 2P25 ln",
			[29] = "LAZ Bus",
			[30] = "MAZ-6303",
			[31] = "MTLB",
			[32] = "Osa 9A33 ln",
			[33] = "SA-11 Buk CC 9S470M1",
			[34] = "SA-11 Buk LN 9A310M1",
			[35] = "SA-11 Buk SR 9S18M1",
			[36] = "SA-18 Igla comm",
			[37] = "SA-18 Igla manpad",
			[38] = "SAU 2-C9",
			[39] = "SAU Akatsia",
			[40] = "SAU Gvozdika",
			[41] = "SKP-11",
			[42] = "Soldier AK",
			[43] = "Soldier RPG",
			[44] = "Strela-1 9P31",
			[45] = "Strela-10M3",
			[46] = "T-55",
			[47] = "T-72B",
			[48] = "Trolley bus",
			[49] = "UAZ-469",
			[50] = "Ural ATsP-6",
			[51] = "Ural-375 PBU",
			[52] = "Ural-375 ZU-23",
			[53] = "Ural-375",
			[54] = "Ural-4320 APA-5D",
			[55] = "Ural-4320T",
			[56] = "VAZ Car",
			[57] = "ZiL-131 APA-80",
			[58] = "ZIL-131 KUNG",
			[59] = "ZIL-4331",
			[60] = "ZSU-23-4 Shilka",
			[61] = "ZU-23 Emplacement Closed",
			[62] = "ZU-23 Emplacement",
		}, -- end of ["Cars"]
		["Animals"] = 
		{
		}, -- end of ["Animals"]
		["WWIIstructures"] = 
		{
		}, -- end of ["WWIIstructures"]
		["Planes"] = 
		{
			[1] = "Su-25",
			[2] = "An-26B",
			[3] = "L-39ZA",
			[4] = "P-51D",
			[5] = "L-39C",
			[6] = "Yak-52",
		}, -- end of ["Planes"]
		["LTAvehicles"] = 
		{
		}, -- end of ["LTAvehicles"]
		["Warehouses"] = 
		{
			[1] = "Warehouse",
			[2] = "Tank",
			[3] = ".Ammunition depot",
			[4] = "Tank 2",
			[5] = "Tank 3",
		}, -- end of ["Warehouses"]
	}, -- end of ["objects"]
	["name"] = "Abkhazia",
	["shortName"] = "ABH",
} -- end of Abkhazia
