Georgia = 
{
	["id"] = 16,
	["objects"] = 
	{
		["Cargos"] = 
		{
			[1] = "uh1h_cargo",
			[2] = "ammo_cargo",
			[3] = "barrels_cargo",
			[4] = "m117_cargo",
			[5] = "iso_container",
			[6] = "iso_container_small",
			[7] = "f_bar_cargo",
			[8] = "container_cargo",
			[9] = "tetrapod_cargo",
			[10] = "fueltank_cargo",
			[11] = "oiltank_cargo",
			[12] = "pipes_small_cargo",
			[13] = "pipes_big_cargo",
			[14] = "trunks_small_cargo",
			[15] = "trunks_long_cargo",
		}, -- end of ["Cargos"]
		["Heliports"] = 
		{
			[1] = "FARP",
			[2] = "SINGLE_HELIPAD",
		}, -- end of ["Heliports"]
		["Ships"] = 
		{
			[1] = "speedboat",
			[2] = "ELNYA",
			[3] = "ALBATROS",
			[4] = "MOLNIYA",
			[5] = "Dry-cargo ship-1",
			[6] = "Dry-cargo ship-2",
			[7] = "ZWEZDNY",
		}, -- end of ["Ships"]
		["Helicopters"] = 
		{
			[1] = "Ka-50",
			[2] = "UH-1H",
			[3] = "Mi-8MT",
			[4] = "Mi-24V",
			[5] = "Mi-24P",
		}, -- end of ["Helicopters"]
		["GrassAirfields"] = 
		{
			[1] = "GrassAirfield",
		}, -- end of ["GrassAirfields"]
		["Fortifications"] = 
		{
			[1] = "Locomotive",
			[2] = "Electric locomotive",
			[3] = "Coach a tank yellow",
			[4] = "Coach a tank blue",
			[5] = "Coach cargo",
			[6] = "Coach cargo open",
			[7] = "Coach a platform",
			[8] = "Coach a passenger",
			[9] = ".Command Center",
			[10] = "Hangar A",
			[11] = "Tech hangar A",
			[12] = "Farm A",
			[13] = "Farm B",
			[14] = "Garage A",
			[15] = "Boiler-house A",
			[16] = "Restaurant 1",
			[17] = "Comms tower M",
			[18] = "Cafe",
			[19] = "Workshop A",
			[20] = "Electric power box",
			[21] = "Supermarket A",
			[22] = "Water tower A",
			[23] = "TV tower",
			[24] = "Shelter",
			[25] = "Repair workshop",
			[26] = "Railway station",
			[27] = "Railway crossing A",
			[28] = "Railway crossing B",
			[29] = "WC",
			[30] = "Small house 1A area",
			[31] = "Small house 1A",
			[32] = "Small house 1B area",
			[33] = "Small house 1B",
			[34] = "Small house 1C area",
			[35] = "Small house 2C",
			[36] = "Shop",
			[37] = "Tech combine",
			[38] = "Chemical tank A",
			[39] = "Small werehouse 1",
			[40] = "Small werehouse 2",
			[41] = "Small werehouse 3",
			[42] = "Small werehouse 4",
			[43] = "Garage B",
			[44] = "Garage small A",
			[45] = "Garage small B",
			[46] = "Pump station",
			[47] = "Oil derrick",
			[48] = "Container red 1",
			[49] = "Container red 2",
			[50] = "Container red 3",
			[51] = "Container white",
			[52] = "Container brown",
			[53] = "Barracks 2",
			[54] = "Military staff",
			[55] = "Hangar B",
			[56] = "Fuel tank",
			[57] = "Shelter B",
			[58] = "Oil platform",
			[59] = "Subsidiary structure 1",
			[60] = "Subsidiary structure 2",
			[61] = "Subsidiary structure 3",
			[62] = "Subsidiary structure A",
			[63] = "Subsidiary structure B",
			[64] = "Subsidiary structure C",
			[65] = "Subsidiary structure D",
			[66] = "Subsidiary structure E",
			[67] = "Subsidiary structure F",
			[68] = "Subsidiary structure G",
			[69] = "Landmine",
			[70] = "FARP Ammo Dump Coating",
			[71] = "FARP Tent",
			[72] = "FARP CP Blindage",
			[73] = "FARP Fuel Depot",
			[74] = "GeneratorF",
			[75] = "Airshow_Cone",
			[76] = "Airshow_Crowd",
			[77] = "Red_Flag",
			[78] = "White_Flag",
			[79] = "Black_Tyre",
			[80] = "White_Tyre",
			[81] = "Black_Tyre_RF",
			[82] = "Black_Tyre_WF",
			[83] = "Windsock",
		}, -- end of ["Fortifications"]
		["Effects"] = 
		{
			[1] = "big_smoke",
			[2] = "smoky_marker",
			[3] = "smoking_line",
			[4] = "dust_smoke",
		}, -- end of ["Effects"]
		["Cars"] = 
		{
			[1] = "Bunker",
			[2] = "Sandbox",
			[3] = "house1arm",
			[4] = "house2arm",
			[5] = "outpost_road",
			[6] = "outpost",
			[7] = "houseA_arm",
			[8] = "TACAN_beacon",
			[9] = "1L13 EWR",
			[10] = "2B11 mortar",
			[11] = "5p73 s-125 ln",
			[12] = "ATMZ-5",
			[13] = "ATZ-10",
			[14] = "BMD-1",
			[15] = "BMP-1",
			[16] = "BMP-2",
			[17] = "BRDM-2",
			[18] = "BTR-80",
			[19] = "Cobra",
			[20] = "Dog Ear radar",
			[21] = "GAZ-3307",
			[22] = "GAZ-3308",
			[23] = "GAZ-66",
			[24] = "Grad-URAL",
			[25] = "IKARUS Bus",
			[26] = "KAMAZ Truck",
			[27] = "KrAZ6322",
			[28] = "LAZ Bus",
			[29] = "M 818",
			[30] = "M1043 HMMWV Armament",
			[31] = "MAZ-6303",
			[32] = "MTLB",
			[33] = "Osa 9A33 ln",
			[34] = "p-19 s-125 sr",
			[35] = "SA-11 Buk CC 9S470M1",
			[36] = "SA-11 Buk LN 9A310M1",
			[37] = "SA-11 Buk SR 9S18M1",
			[38] = "SA-18 Igla comm",
			[39] = "SA-18 Igla manpad",
			[40] = "SAU Akatsia",
			[41] = "SAU Msta",
			[42] = "SKP-11",
			[43] = "snr s-125 tr",
			[44] = "Soldier M4 GRG",
			[45] = "Soldier RPG",
			[46] = "Soldier stinger",
			[47] = "SpGH_Dana",
			[48] = "Stinger comm",
			[49] = "Strela-1 9P31",
			[50] = "Strela-10M3",
			[51] = "T-55",
			[52] = "T-72B",
			[53] = "Trolley bus",
			[54] = "UAZ-469",
			[55] = "Ural ATsP-6",
			[56] = "Ural-375 PBU",
			[57] = "Ural-375 ZU-23",
			[58] = "Ural-375",
			[59] = "Ural-4320 APA-5D",
			[60] = "VAZ Car",
			[61] = "ZiL-131 APA-80",
			[62] = "ZIL-131 KUNG",
			[63] = "ZIL-4331",
			[64] = "ZSU-23-4 Shilka",
			[65] = "ZU-23 Emplacement Closed",
			[66] = "ZU-23 Emplacement",
			[67] = "Hummer",
			[68] = "Coach a tank yellow",
			[69] = "Coach a tank blue",
			[70] = "Coach cargo",
			[71] = "Coach cargo open",
			[72] = "Coach a platform",
			[73] = "Coach a passenger",
			[74] = "Uragan_BM-27",
			[75] = "SAU 2-C9",
			[76] = "SAU Gvozdika",
			[77] = "SNR_75V",
			[78] = "S_75M_Volhov",
			[79] = "Ural-4320-31",
			[80] = "Ural-4320T",
			[81] = "Electric locomotive",
			[82] = "Locomotive",
		}, -- end of ["Cars"]
		["Animals"] = 
		{
		}, -- end of ["Animals"]
		["WWIIstructures"] = 
		{
		}, -- end of ["WWIIstructures"]
		["Planes"] = 
		{
			[1] = "A-10C",
			[2] = "Su-25",
			[3] = "An-26B",
			[4] = "Su-25T",
			[5] = "L-39ZA",
			[6] = "Yak-40",
			[7] = "P-51D",
			[8] = "L-39C",
			[9] = "Yak-52",
		}, -- end of ["Planes"]
		["LTAvehicles"] = 
		{
		}, -- end of ["LTAvehicles"]
		["Warehouses"] = 
		{
			[1] = "Warehouse",
			[2] = "Tank",
			[3] = ".Ammunition depot",
			[4] = "Tank 2",
			[5] = "Tank 3",
		}, -- end of ["Warehouses"]
	}, -- end of ["objects"]
	["name"] = "Georgia",
	["shortName"] = "GRG",
} -- end of Georgia
