Iran = 
{
	["id"] = 34,
	["objects"] = 
	{
		["Cargos"] = 
		{
			[1] = "uh1h_cargo",
			[2] = "ammo_cargo",
			[3] = "barrels_cargo",
			[4] = "m117_cargo",
			[5] = "iso_container",
			[6] = "iso_container_small",
			[7] = "f_bar_cargo",
			[8] = "container_cargo",
			[9] = "tetrapod_cargo",
			[10] = "fueltank_cargo",
			[11] = "oiltank_cargo",
			[12] = "pipes_small_cargo",
			[13] = "pipes_big_cargo",
			[14] = "trunks_small_cargo",
			[15] = "trunks_long_cargo",
		}, -- end of ["Cargos"]
		["Heliports"] = 
		{
			[1] = "FARP",
			[2] = "SINGLE_HELIPAD",
		}, -- end of ["Heliports"]
		["Ships"] = 
		{
			[1] = "speedboat",
			[2] = "KILO",
			[3] = "Dry-cargo ship-1",
			[4] = "Dry-cargo ship-2",
		}, -- end of ["Ships"]
		["Helicopters"] = 
		{
			[1] = "Ka-50",
			[2] = "UH-1H",
			[3] = "AH-1W",
			[4] = "OH-58D",
			[5] = "Mi-8MT",
			[6] = "CH-47D",
		}, -- end of ["Helicopters"]
		["GrassAirfields"] = 
		{
			[1] = "GrassAirfield",
		}, -- end of ["GrassAirfields"]
		["Fortifications"] = 
		{
			[1] = "Locomotive",
			[2] = "Electric locomotive",
			[3] = "Coach a tank yellow",
			[4] = "Coach a tank blue",
			[5] = "Coach cargo",
			[6] = "Coach cargo open",
			[7] = "Coach a platform",
			[8] = "Coach a passenger",
			[9] = ".Command Center",
			[10] = "Hangar A",
			[11] = "Tech hangar A",
			[12] = "Farm A",
			[13] = "Farm B",
			[14] = "Garage A",
			[15] = "Boiler-house A",
			[16] = "Restaurant 1",
			[17] = "Comms tower M",
			[18] = "Cafe",
			[19] = "Workshop A",
			[20] = "Electric power box",
			[21] = "Supermarket A",
			[22] = "Water tower A",
			[23] = "TV tower",
			[24] = "Shelter",
			[25] = "Repair workshop",
			[26] = "Railway station",
			[27] = "Railway crossing A",
			[28] = "Railway crossing B",
			[29] = "WC",
			[30] = "Small house 1A area",
			[31] = "Small house 1A",
			[32] = "Small house 1B area",
			[33] = "Small house 1B",
			[34] = "Small house 1C area",
			[35] = "Small house 2C",
			[36] = "Shop",
			[37] = "Tech combine",
			[38] = "Chemical tank A",
			[39] = "Small werehouse 1",
			[40] = "Small werehouse 2",
			[41] = "Small werehouse 3",
			[42] = "Small werehouse 4",
			[43] = "Garage B",
			[44] = "Garage small A",
			[45] = "Garage small B",
			[46] = "Pump station",
			[47] = "Oil derrick",
			[48] = "Container red 1",
			[49] = "Container red 2",
			[50] = "Container red 3",
			[51] = "Container white",
			[52] = "Container brown",
			[53] = "Barracks 2",
			[54] = "Military staff",
			[55] = "Hangar B",
			[56] = "Fuel tank",
			[57] = "Shelter B",
			[58] = "Oil platform",
			[59] = "Subsidiary structure 1",
			[60] = "Subsidiary structure 2",
			[61] = "Subsidiary structure 3",
			[62] = "Subsidiary structure A",
			[63] = "Subsidiary structure B",
			[64] = "Subsidiary structure C",
			[65] = "Subsidiary structure D",
			[66] = "Subsidiary structure E",
			[67] = "Subsidiary structure F",
			[68] = "Subsidiary structure G",
			[69] = "Landmine",
			[70] = "FARP Ammo Dump Coating",
			[71] = "FARP Tent",
			[72] = "FARP CP Blindage",
			[73] = "FARP Fuel Depot",
			[74] = "GeneratorF",
			[75] = "Airshow_Cone",
			[76] = "Airshow_Crowd",
			[77] = "Red_Flag",
			[78] = "White_Flag",
			[79] = "Black_Tyre",
			[80] = "White_Tyre",
			[81] = "Black_Tyre_RF",
			[82] = "Black_Tyre_WF",
			[83] = "Windsock",
		}, -- end of ["Fortifications"]
		["Effects"] = 
		{
			[1] = "big_smoke",
			[2] = "smoky_marker",
			[3] = "smoking_line",
			[4] = "dust_smoke",
		}, -- end of ["Effects"]
		["Cars"] = 
		{
			[1] = "Bunker",
			[2] = "Sandbox",
			[3] = "house1arm",
			[4] = "house2arm",
			[5] = "outpost_road",
			[6] = "outpost",
			[7] = "houseA_arm",
			[8] = "TACAN_beacon",
			[9] = "BMP-1",
			[10] = "BMP-2",
			[11] = "BTR-80",
			[12] = "T-72B",
			[13] = "T-55",
			[14] = "M-113",
			[15] = "M-60",
			[16] = "SAU Gvozdika",
			[17] = "M-109",
			[18] = "Grad-URAL",
			[19] = "Infantry AK Ins",
			[20] = "Soldier RPG",
			[21] = "ZU-23 Closed Insurgent",
			[22] = "Ural-375 ZU-23 Insurgent",
			[23] = "S-300PS 40B6M tr",
			[24] = "S-300PS 40B6MD sr",
			[25] = "S-300PS 64H6E sr",
			[26] = "S-300PS 5P85C ln",
			[27] = "S-300PS 5P85D ln",
			[28] = "S-300PS 54K6 cp",
			[29] = "Kub 1S91 str",
			[30] = "Kub 2P25 ln",
			[31] = "Igla manpad INS",
			[32] = "SA-18 Igla comm",
			[33] = "Hawk sr",
			[34] = "Hawk cwar",
			[35] = "Hawk pcp",
			[36] = "Hawk tr",
			[37] = "Hawk ln",
			[38] = "SA-11 Buk SR 9S18M1",
			[39] = "SA-11 Buk CC 9S470M1",
			[40] = "SA-11 Buk LN 9A310M1",
			[41] = "p-19 s-125 sr",
			[42] = "Ural-375",
			[43] = "Tor 9A331",
			[44] = "BMD-1",
			[45] = "M4_Sherman",
			[46] = "Pz_IV_H",
			[47] = "SNR_75V",
			[48] = "S_75M_Volhov",
			[49] = "rapier_fsa_launcher",
			[50] = "rapier_fsa_optical_tracker_unit",
			[51] = "rapier_fsa_blindfire_radar",
			[52] = "ZSU-23-4 Shilka",
			[53] = "KrAZ6322",
			[54] = "ScudLauncher",
			[55] = "hy_launcher",
			[56] = "Silkworm_SR",
		}, -- end of ["Cars"]
		["Animals"] = 
		{
		}, -- end of ["Animals"]
		["WWIIstructures"] = 
		{
		}, -- end of ["WWIIstructures"]
		["Planes"] = 
		{
			[1] = "A-10C",
			[2] = "MiG-29A",
			[3] = "Su-25",
			[4] = "Su-24M",
			[5] = "IL-76MD",
			[6] = "MiG-21Bis",
			[7] = "A-50",
			[8] = "F-14A",
			[9] = "F-4E",
			[10] = "C-130",
			[11] = "B-17G",
			[12] = "F-5E",
			[13] = "F-5E-3",
			[14] = "F-5E_MAC",
			[15] = "F-86F Sabre",
			[16] = "F-86F_MAC",
			[17] = "Su-25T",
		}, -- end of ["Planes"]
		["LTAvehicles"] = 
		{
		}, -- end of ["LTAvehicles"]
		["Warehouses"] = 
		{
			[1] = "Warehouse",
			[2] = "Tank",
			[3] = ".Ammunition depot",
			[4] = "Tank 2",
			[5] = "Tank 3",
		}, -- end of ["Warehouses"]
	}, -- end of ["objects"]
	["name"] = "Iran",
	["shortName"] = "IRN",
} -- end of Iran
