Poland = 
{
	["id"] = 40,
	["objects"] = 
	{
		["Cargos"] = 
		{
			[1] = "uh1h_cargo",
			[2] = "ammo_cargo",
			[3] = "barrels_cargo",
			[4] = "m117_cargo",
			[5] = "iso_container",
			[6] = "iso_container_small",
			[7] = "f_bar_cargo",
			[8] = "container_cargo",
			[9] = "tetrapod_cargo",
			[10] = "fueltank_cargo",
			[11] = "oiltank_cargo",
			[12] = "pipes_small_cargo",
			[13] = "pipes_big_cargo",
			[14] = "trunks_small_cargo",
			[15] = "trunks_long_cargo",
		}, -- end of ["Cargos"]
		["Heliports"] = 
		{
			[1] = "FARP",
			[2] = "SINGLE_HELIPAD",
		}, -- end of ["Heliports"]
		["Ships"] = 
		{
			[1] = "speedboat",
		}, -- end of ["Ships"]
		["Helicopters"] = 
		{
			[1] = "Ka-50",
			[2] = "Mi-8MT",
		}, -- end of ["Helicopters"]
		["GrassAirfields"] = 
		{
			[1] = "GrassAirfield",
		}, -- end of ["GrassAirfields"]
		["Fortifications"] = 
		{
			[1] = "Locomotive",
			[2] = "Electric locomotive",
			[3] = "Coach a tank yellow",
			[4] = "Coach a tank blue",
			[5] = "Coach cargo",
			[6] = "Coach cargo open",
			[7] = "Coach a platform",
			[8] = "Coach a passenger",
			[9] = ".Command Center",
			[10] = "Hangar A",
			[11] = "Tech hangar A",
			[12] = "Farm A",
			[13] = "Farm B",
			[14] = "Garage A",
			[15] = "Boiler-house A",
			[16] = "Restaurant 1",
			[17] = "Comms tower M",
			[18] = "Cafe",
			[19] = "Workshop A",
			[20] = "Electric power box",
			[21] = "Supermarket A",
			[22] = "Water tower A",
			[23] = "TV tower",
			[24] = "Shelter",
			[25] = "Repair workshop",
			[26] = "Railway station",
			[27] = "Railway crossing A",
			[28] = "Railway crossing B",
			[29] = "WC",
			[30] = "Small house 1A area",
			[31] = "Small house 1A",
			[32] = "Small house 1B area",
			[33] = "Small house 1B",
			[34] = "Small house 1C area",
			[35] = "Small house 2C",
			[36] = "Shop",
			[37] = "Tech combine",
			[38] = "Chemical tank A",
			[39] = "Small werehouse 1",
			[40] = "Small werehouse 2",
			[41] = "Small werehouse 3",
			[42] = "Small werehouse 4",
			[43] = "Garage B",
			[44] = "Garage small A",
			[45] = "Garage small B",
			[46] = "Pump station",
			[47] = "Oil derrick",
			[48] = "Container red 1",
			[49] = "Container red 2",
			[50] = "Container red 3",
			[51] = "Container white",
			[52] = "Container brown",
			[53] = "Barracks 2",
			[54] = "Military staff",
			[55] = "Hangar B",
			[56] = "Fuel tank",
			[57] = "Shelter B",
			[58] = "Oil platform",
			[59] = "Subsidiary structure 1",
			[60] = "Subsidiary structure 2",
			[61] = "Subsidiary structure 3",
			[62] = "Subsidiary structure A",
			[63] = "Subsidiary structure B",
			[64] = "Subsidiary structure C",
			[65] = "Subsidiary structure D",
			[66] = "Subsidiary structure E",
			[67] = "Subsidiary structure F",
			[68] = "Subsidiary structure G",
			[69] = "Landmine",
			[70] = "FARP Ammo Dump Coating",
			[71] = "FARP Tent",
			[72] = "FARP CP Blindage",
			[73] = "FARP Fuel Depot",
			[74] = "GeneratorF",
			[75] = "Airshow_Cone",
			[76] = "Airshow_Crowd",
			[77] = "Red_Flag",
			[78] = "White_Flag",
			[79] = "Black_Tyre",
			[80] = "White_Tyre",
			[81] = "Black_Tyre_RF",
			[82] = "Black_Tyre_WF",
			[83] = "Windsock",
		}, -- end of ["Fortifications"]
		["Effects"] = 
		{
			[1] = "big_smoke",
			[2] = "smoky_marker",
			[3] = "smoking_line",
			[4] = "dust_smoke",
		}, -- end of ["Effects"]
		["Cars"] = 
		{
			[1] = "Bunker",
			[2] = "Sandbox",
			[3] = "house1arm",
			[4] = "house2arm",
			[5] = "outpost_road",
			[6] = "outpost",
			[7] = "houseA_arm",
			[8] = "TACAN_beacon",
			[9] = "SpGH_Dana",
			[10] = "p-19 s-125 sr",
			[11] = "Ural-375",
			[12] = "Hummer",
			[13] = "M1043 HMMWV Armament",
			[14] = "M1045 HMMWV TOW",
			[15] = "M-113",
			[16] = "M2A1_halftrack",
			[17] = "MTLB",
			[18] = "BRDM-2",
			[19] = "Cromwell_IV",
			[20] = "Centaur_IV",
			[21] = "BMP-1",
			[22] = "BMP-2",
			[23] = "Leopard-2",
			[24] = "T-55",
			[25] = "M4_Sherman",
			[26] = "M4A4_Sherman_FF",
			[27] = "2B11 mortar",
			[28] = "Grad-URAL",
			[29] = "SAU Gvozdika",
			[30] = "bofors40",
			[31] = "ZU-23 Emplacement Closed",
			[32] = "ZU-23 Emplacement",
			[33] = "Ural-375 ZU-23",
			[34] = "SNR_75V",
			[35] = "S_75M_Volhov",
			[36] = "5p73 s-125 ln",
			[37] = "snr s-125 tr",
			[38] = "Kub 2P25 ln",
			[39] = "Kub 1S91 str",
			[40] = "Osa 9A33 ln",
			[41] = "Strela-1 9P31",
			[42] = "ZSU-23-4 Shilka",
			[43] = "IKARUS Bus",
			[44] = "KAMAZ Truck",
			[45] = "MAZ-6303",
			[46] = "UAZ-469",
			[47] = "Trolley bus",
			[48] = "ScudLauncher",
			[49] = "VAZ Car",
			[50] = "DRG_Class_86",
			[51] = "German_covered_wagon_G10",
			[52] = "DR_50Ton_Flat_Wagon",
			[53] = "German_tank_wagon",
		}, -- end of ["Cars"]
		["Animals"] = 
		{
		}, -- end of ["Animals"]
		["WWIIstructures"] = 
		{
		}, -- end of ["WWIIstructures"]
		["Planes"] = 
		{
			[1] = "A-10C",
			[2] = "F-16C bl.50",
			[3] = "MiG-29A",
			[4] = "Su-17M4",
			[5] = "P-51D",
			[6] = "P-51D-30-NA",
			[7] = "An-26B",
			[8] = "C-130",
			[9] = "C-17A",
			[10] = "E-3A",
			[11] = "MiG-15bis",
			[12] = "MiG-15bis_MAC",
			[13] = "MiG-21Bis",
			[14] = "MiG-29G",
			[15] = "Yak-40",
			[16] = "I-16",
		}, -- end of ["Planes"]
		["LTAvehicles"] = 
		{
		}, -- end of ["LTAvehicles"]
		["Warehouses"] = 
		{
			[1] = "Warehouse",
			[2] = "Tank",
			[3] = ".Ammunition depot",
			[4] = "Tank 2",
			[5] = "Tank 3",
		}, -- end of ["Warehouses"]
	}, -- end of ["objects"]
	["name"] = "Poland",
	["shortName"] = "POL",
} -- end of Poland
