USA = 
{
	["id"] = 2,
	["objects"] = 
	{
		["Cargos"] = 
		{
			[1] = "uh1h_cargo",
			[2] = "ammo_cargo",
			[3] = "barrels_cargo",
			[4] = "m117_cargo",
			[5] = "iso_container",
			[6] = "iso_container_small",
			[7] = "f_bar_cargo",
			[8] = "container_cargo",
			[9] = "tetrapod_cargo",
			[10] = "fueltank_cargo",
			[11] = "oiltank_cargo",
			[12] = "pipes_small_cargo",
			[13] = "pipes_big_cargo",
			[14] = "trunks_small_cargo",
			[15] = "trunks_long_cargo",
		}, -- end of ["Cargos"]
		["Heliports"] = 
		{
			[1] = "FARP",
			[2] = "SINGLE_HELIPAD",
		}, -- end of ["Heliports"]
		["Ships"] = 
		{
			[1] = "speedboat",
			[2] = "VINSON",
			[3] = "PERRY",
			[4] = "TICONDEROG",
			[5] = "Higgins_boat",
			[6] = "LST_Mk2",
			[7] = "Stennis",
			[8] = "USS_Samuel_Chase",
			[9] = "LHA_Tarawa",
			[10] = "USS_Arleigh_Burke_IIa",
		}, -- end of ["Ships"]
		["Helicopters"] = 
		{
			[1] = "Ka-50",
			[2] = "AH-64A",
			[3] = "AH-64D",
			[4] = "AH-1W",
			[5] = "UH-60A",
			[6] = "CH-47D",
			[7] = "SH-60B",
			[8] = "CH-53E",
			[9] = "OH-58D",
			[10] = "UH-1H",
			[11] = "Mi-8MT",
			[12] = "Mi-24P",
		}, -- end of ["Helicopters"]
		["GrassAirfields"] = 
		{
			[1] = "GrassAirfield",
		}, -- end of ["GrassAirfields"]
		["Fortifications"] = 
		{
			[1] = "Locomotive",
			[2] = "Electric locomotive",
			[3] = "Coach a tank yellow",
			[4] = "Coach a tank blue",
			[5] = "Coach cargo",
			[6] = "Coach cargo open",
			[7] = "Coach a platform",
			[8] = "Coach a passenger",
			[9] = ".Command Center",
			[10] = "Hangar A",
			[11] = "Tech hangar A",
			[12] = "Farm A",
			[13] = "Farm B",
			[14] = "Garage A",
			[15] = "Boiler-house A",
			[16] = "Restaurant 1",
			[17] = "Comms tower M",
			[18] = "Cafe",
			[19] = "Workshop A",
			[20] = "Electric power box",
			[21] = "Supermarket A",
			[22] = "Water tower A",
			[23] = "TV tower",
			[24] = "Shelter",
			[25] = "Repair workshop",
			[26] = "Railway station",
			[27] = "Railway crossing A",
			[28] = "Railway crossing B",
			[29] = "WC",
			[30] = "Small house 1A area",
			[31] = "Small house 1A",
			[32] = "Small house 1B area",
			[33] = "Small house 1B",
			[34] = "Small house 1C area",
			[35] = "Small house 2C",
			[36] = "Shop",
			[37] = "Tech combine",
			[38] = "Chemical tank A",
			[39] = "Small werehouse 1",
			[40] = "Small werehouse 2",
			[41] = "Small werehouse 3",
			[42] = "Small werehouse 4",
			[43] = "Garage B",
			[44] = "Garage small A",
			[45] = "Garage small B",
			[46] = "Pump station",
			[47] = "Oil derrick",
			[48] = "Container red 1",
			[49] = "Container red 2",
			[50] = "Container red 3",
			[51] = "Container white",
			[52] = "Container brown",
			[53] = "Barracks 2",
			[54] = "Military staff",
			[55] = "Hangar B",
			[56] = "Fuel tank",
			[57] = "Shelter B",
			[58] = "Oil platform",
			[59] = "Subsidiary structure 1",
			[60] = "Subsidiary structure 2",
			[61] = "Subsidiary structure 3",
			[62] = "Subsidiary structure A",
			[63] = "Subsidiary structure B",
			[64] = "Subsidiary structure C",
			[65] = "Subsidiary structure D",
			[66] = "Subsidiary structure E",
			[67] = "Subsidiary structure F",
			[68] = "Subsidiary structure G",
			[69] = "Landmine",
			[70] = "FARP Ammo Dump Coating",
			[71] = "FARP Tent",
			[72] = "FARP CP Blindage",
			[73] = "FARP Fuel Depot",
			[74] = "GeneratorF",
			[75] = "Airshow_Cone",
			[76] = "Airshow_Crowd",
			[77] = "Red_Flag",
			[78] = "White_Flag",
			[79] = "Black_Tyre",
			[80] = "White_Tyre",
			[81] = "Black_Tyre_RF",
			[82] = "Black_Tyre_WF",
			[83] = "Windsock",
		}, -- end of ["Fortifications"]
		["Effects"] = 
		{
			[1] = "big_smoke",
			[2] = "smoky_marker",
			[3] = "smoking_line",
			[4] = "dust_smoke",
		}, -- end of ["Effects"]
		["Cars"] = 
		{
			[1] = "Bunker",
			[2] = "Sandbox",
			[3] = "house1arm",
			[4] = "house2arm",
			[5] = "outpost_road",
			[6] = "outpost",
			[7] = "houseA_arm",
			[8] = "TACAN_beacon",
			[9] = "2B11 mortar",
			[10] = "AAV7",
			[11] = "Hawk cwar",
			[12] = "Hawk ln",
			[13] = "Hawk pcp",
			[14] = "Hawk sr",
			[15] = "Hawk tr",
			[16] = "HEMTT TFFT",
			[17] = "Hummer",
			[18] = "LAV-25",
			[19] = "M 818",
			[20] = "M-1 Abrams",
			[21] = "M-109",
			[22] = "M-113",
			[23] = "M-2 Bradley",
			[24] = "M-60",
			[25] = "M1043 HMMWV Armament",
			[26] = "M1045 HMMWV TOW",
			[27] = "M1097 Avenger",
			[28] = "M1126 Stryker ICV",
			[29] = "M1128 Stryker MGS",
			[30] = "M1134 Stryker ATGM",
			[31] = "M48 Chaparral",
			[32] = "M6 Linebacker",
			[33] = "M978 HEMTT Tanker",
			[34] = "MLRS FDDM",
			[35] = "MLRS",
			[36] = "Patriot AMG",
			[37] = "Patriot cp",
			[38] = "Patriot ECS",
			[39] = "Patriot EPP",
			[40] = "Patriot ln",
			[41] = "Patriot str",
			[42] = "Predator GCS",
			[43] = "Predator TrojanSpirit",
			[44] = "Soldier M249",
			[45] = "Soldier M4",
			[46] = "Soldier stinger",
			[47] = "Stinger comm",
			[48] = "Vulcan",
			[49] = "M2A1_halftrack",
			[50] = "MTLB",
			[51] = "TPZ",
			[52] = "BRDM-2",
			[53] = "M30_CC",
			[54] = "M4_Sherman",
			[55] = "M4A4_Sherman_FF",
			[56] = "Pz_IV_H",
			[57] = "M12_GMC",
			[58] = "bofors40",
			[59] = "flak36",
			[60] = "ZU-23 Emplacement Closed",
			[61] = "ZU-23 Emplacement",
			[62] = "Roland ADS",
			[63] = "Roland Radar",
			[64] = "SA-18 Igla manpad",
			[65] = "SA-18 Igla comm",
			[66] = "rapier_fsa_launcher",
			[67] = "rapier_fsa_optical_tracker_unit",
			[68] = "rapier_fsa_blindfire_radar",
			[69] = "CCKW_353",
			[70] = "Willys_MB",
			[71] = "ScudLauncher",
			[72] = "TomahawkLauncher",
			[73] = "M10_GMC",
			[74] = "ES44AH",
			[75] = "Wellcarnsc",
			[76] = "Boxcartrinity",
			[77] = "Tankcartrinity",
		}, -- end of ["Cars"]
		["Animals"] = 
		{
		}, -- end of ["Animals"]
		["WWIIstructures"] = 
		{
		}, -- end of ["WWIIstructures"]
		["Planes"] = 
		{
			[1] = "A-10C",
			[2] = "A-10A",
			[3] = "B-1B",
			[4] = "B-52H",
			[5] = "C-130",
			[6] = "C-17A",
			[7] = "E-2C",
			[8] = "E-3A",
			[9] = "F-117A",
			[10] = "F-14A",
			[11] = "F-15C",
			[12] = "F-15E",
			[13] = "F-16A",
			[14] = "F-16C bl.52d",
			[15] = "F/A-18C",
			[16] = "KC-135",
			[17] = "L-39ZA",
			[18] = "P-51D",
			[19] = "RQ-1A Predator",
			[20] = "S-3B Tanker",
			[21] = "S-3B",
			[22] = "P-51D-30-NA",
			[23] = "A-10C",
			[24] = "An-26B",
			[25] = "B-17G",
			[26] = "F-16A MLU",
			[27] = "F-16C bl.50",
			[28] = "F-16C_50",
			[29] = "F-4E",
			[30] = "F-5E",
			[31] = "F-5E-3",
			[32] = "F-5E_MAC",
			[33] = "F-86F Sabre",
			[34] = "F-86F_MAC",
			[35] = "F/A-18A",
			[36] = "FA-18C_hornet",
			[37] = "IL-78M",
			[38] = "KC135MPRS",
			[39] = "L-39C",
			[40] = "SpitfireLFMkIX",
			[41] = "SpitfireLFMkIXCW",
			[42] = "Su-27",
			[43] = "TF-51",
			[44] = "MQ-9 Reaper",
			[45] = "Christen Eagle II",
			[46] = "AV8BNA",
			[47] = "Hawk",
			[48] = "KC130",
		}, -- end of ["Planes"]
		["LTAvehicles"] = 
		{
		}, -- end of ["LTAvehicles"]
		["Warehouses"] = 
		{
			[1] = "Warehouse",
			[2] = "Tank",
			[3] = ".Ammunition depot",
			[4] = "Tank 2",
			[5] = "Tank 3",
		}, -- end of ["Warehouses"]
	}, -- end of ["objects"]
	["name"] = "USA",
	["shortName"] = "USA",
} -- end of USA
